feat: institution selector
Pearson-Advance/frontend-app-instructors-portal pull request #16
Opened 2024-08-15 00:04 UTC by 01001110J

# Description

In this PR is added the drop down selector for multiple institutions

This PR resolves [PADV-1505](https://agile-jira.pearson.com/browse/PADV-1505)

## Change log
- Added new drop down.
- The institution id is preserved on the url.
- Updated unit test.

### How to test

Clone the Institution Portal MFE
```Bash
     git clone <url>
```
Install the packages 📦.
```Bash
     npm i
```
Start project.
```Bash
     npm start
```

Finally, go to http://localhost:1980/ and use the different current links to navigate around, you should be able to have the institution Id in the ulr in case to have multiple institutions linked to your account..

2024-08-15 16:53 UTC, AuraAlba requested changes

2024-08-15 16:53 UTC, AuraAlba commented on src/hooks/index.jsx
This hook could be moved to the library

2024-08-15 16:53 UTC, AuraAlba commented on src/helpers/index.jsx
> +export const formatSelectOptions = (options) => {
Move this to the helpers in library

2024-08-15 16:53 UTC, AuraAlba commented on src/features/Main/InstitutionSelector/index.jsx
In filters, students and classes, the select options is not loaded correctly when you change the institutionId, also when you apply filters is not send the institution Id

2024-08-15 18:32 UTC, 01001110J commented on src/features/Main/InstitutionSelector/index.jsx
> In filters, students and classes, the select options is not loaded correctly when you change the institutionId

Could you please tell me how to reproduce the issue? I been tried on postman and everything looks good, but maybe I'm testing wrong.

2024-08-15 18:33 UTC, 01001110J commented on src/hooks/index.jsx
Not sure about it, it involve to install redux  in the lib, which is not bad but, keep the same lib in 3 different repos, idk it does not convince to me, also is a pretty simple hook and the way in how we access to the state is different in both repositories.

2024-08-15 19:20 UTC, AuraAlba commented on src/features/Main/InstitutionSelector/index.jsx
When you are in students filters you see the courses options, but when you change the institution the options are the same and should be updated, same for classes filters. Let me know if you can't see it

2024-08-15 20:34 UTC, 01001110J commented on src/features/Main/InstitutionSelector/index.jsx
Fixed

2024-08-15 21:18 UTC, AuraAlba commented on src/features/Main/InstitutionSelector/index.jsx
In filters I lost the institution id query when I click reset

2024-08-15 21:39 UTC, 01001110J commented on src/features/Main/InstitutionSelector/index.jsx
Fixed @AuraAlba

2024-08-16 00:50 UTC, AuraAlba approved these changes

2024-08-16 14:15 UTC, anfbermudezme approved these changes

2024-08-16 18:18 UTC, merged