feat: added events service
Pearson-Advance/frontend-app-instructors-portal pull request #23
Opened 2024-09-06 19:29 UTC by 01001110J

2024-09-06 21:13 UTC, AuraAlba requested changes

2024-09-06 21:28 UTC, AuraAlba commented on src/features/Instructor/AddEvent/index.jsx
> +        repeat: eventData.repeat.value,
Add also a field 'availability' with the value of the typeEvent, this will be used for the color format

2024-09-06 21:37 UTC, AuraAlba requested changes

2024-09-06 21:37 UTC, AuraAlba commented on src/features/Instructor/data/api.js
> +function getInstructorEvents(eventData) {
This is not the get method, please change the name to avoid conflicts with the service to get the  events

2024-09-09 14:10 UTC, AuraAlba commented on src/features/Instructor/AddEvent/index.jsx
> +        start: new Date(eventData.startDate).toISOString(),
Please add the first hour to the start date, and the second hour to the end date

2024-09-09 14:13 UTC, AuraAlba commented on src/features/Instructor/AddEvent/index.jsx
>    { label: 'Does not repeat', value: 'not-repeat' },
Add daily, bi-weekly to the options

2024-09-10 22:35 UTC, AuraAlba requested changes

2024-09-10 22:35 UTC, AuraAlba commented on src/features/Instructor/AddEvent/index.jsx
> +  { label: 'Bi weekly', value: 'bi-weekly' },
These should be part of repeatOptions

2024-09-11 18:13 UTC, sergivalero20 approved these changes

2024-09-11 18:39 UTC, merged