feat: students filter
Pearson-Advance/frontend-app-instructors-portal pull request #9
Opened 2024-07-25 21:54 UTC by 01001110J

2024-07-30 19:27 UTC, AuraAlba requested changes

2024-07-31 19:54 UTC, 01001110J commented on src/features/Students/StudentsFilters/index.jsx
Fixed

2024-07-31 21:08 UTC, AuraAlba requested changes

2024-07-31 21:08 UTC, AuraAlba commented on src/features/Students/StudentsPage/index.jsx
> +        <StudentsFilters />
I still see the error, in the pagination I lost the filters
![filters](https://github.com/user-attachments/assets/3a456aaa-3967-4a9b-9154-547d111bf7e9)

You have to add the filters in this page in the fetchStudentsData

2024-08-01 15:59 UTC, AuraAlba approved these changes

2024-08-01 18:28 UTC, anfbermudezme approved these changes

2024-08-01 19:00 UTC, merged